# Generated by Django 4.2.11 on 2024-04-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.kjbcategory')),
            ],
        ),
    ]
