# Generated by Django 4.2.11 on 2024-04-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0002_categorypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('category_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.categorypoints')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.checklist')),
            ],
        ),
    ]
