# Generated by Django 4.2.11 on 2024-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0003_checkliststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkliststatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
