# Generated by Django 4.2.11 on 2024-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0004_checkliststatus_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kjbgoal',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
