# Generated by Django 4.2.11 on 2024-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0005_kjbgoal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
