# Generated by Django 4.2.11 on 2024-04-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0006_checklist_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='category_points',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='okrapp.categorypoints'),
        ),
    ]
