# Generated by Django 4.2.11 on 2024-04-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0008_alter_checklist_category_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.categorypoints')),
            ],
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='sub_category_points',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='okrapp.subcategorypoints'),
        ),
    ]
