# Generated by Django 4.2.11 on 2024-04-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0009_subcategorypoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='category_points',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='checkliststatus',
            name='sub_category_points',
        ),
        migrations.RemoveField(
            model_name='kjbgoal',
            name='name',
        ),
        migrations.DeleteModel(
            name='SubCategoryPoints',
        ),
    ]
