# Generated by Django 4.2.11 on 2024-04-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0011_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.kjbcategory')),
                ('category_points_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.categorypoints')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapp.checklist')),
            ],
        ),
    ]
